### ISSUE TITLE
Desktop Caching is required

### ISSUE THREAD

**Issue by alionour** [hurshi/dio-http-cache#77]
when try to cache http response on windows desktop it returns this error:
**`[ERROR:flutter/lib/ui/ui_dart_state.cc(184)] Unhandled Exception: DioError [DioErrorType.DEFAULT]: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)
#0      DioMixin._request.<anonymous closure>
package:dio/src/dio.dart:910
#1      _rootRunUnary (dart:async/zone.dart:1194:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1097:19)
#3      _FutureListener.handleError (dart:async/future_impl.dart:167:20)
#4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:720:47)
#5      Future._propagateToListeners (dart:async/future_impl.dart:741:24)
#6      Future._completeError (dart:async/future_impl.dart:549:5)
#7      _completeOnAsyncError (dart:async-patch/async_patch.dart:264:13)
#8      DioCacheManager._onError (package:dio_http_cache/src/manager_dio.dart)
package:dio_http_cache/src/manager_dio.dart:1
<asynchronous suspension>
`**
but when using dio with force_refresh = true it works fine

Platform : WIndowsOS

**Comment by clragon** [comment]
The package doesnt inherently support windows, because `sqflite` doesn't.
But the developer of `sqflite` has provided an extra package to add Desktop support, which you can plug into your app.

Heres the link for doing so:
https://github.com/tekartik/sqflite/blob/master/sqflite_common_ffi/doc/using_ffi_instead_of_sqflite.md
